# Generated by Django 4.2.23 on 2025-08-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platera_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
